### PR TITLE
feat:- the post model and connected it with user model

### PR DESCRIPTION
**Pull request by aashimgarg**
the post model and connected it with user model

### CODE REVIEW

**Comment by aashimgarg** [comment]
@shrushti2000 @mohit355 anything else we require in the post model

**Comment by mohit355** [comment]
Suggestion : You can add about field in postSchema for doctor so that they can describe himself/herself

**Comment by aashimgarg** [comment]
> Suggestion : You can add about field in postSchema for doctor so that they can describe himself/herself

as in the description of the doctor ?

**Comment by shrushti2000** [comment]
We can add a field for  website of his/her clinic/hospital (like an optional field).

**Comment by shrushti2000** [comment]
Also a field for gender , regular consultation fees and qualification.(Ig you have not added these fields in the post schema)

**Comment by aashimgarg** [comment]
> Also a field for gender , regular consultation fees and qualification.(Ig you have not added these fields in the post schema)

this is done. just check it once

**Comment by aashimgarg** [comment]
> Suggestion : You can add about field in postSchema for doctor so that they can describe himself/herself

i think we have already added the specialist and qualification field so i think we dont need to add this.

**Comment by shrushti2000** [comment]
> > Also a field for gender , regular consultation fees and qualification.(Ig you have not added these fields in the post schema)
> 
> this is done. just check it once

Ig you have not added field for fees.

**Pull request merged**
