### PR TITLE
Adding more structure to the codebase

### PR DESCRIPTION
**Pull request by nish7898**
We can make the codebase more structured and easy to change. Also, packing all the routes inside the routes folder, and importing a single file in the server.js file.

### CODE REVIEW

**Comment by aashimgarg** [comment]
LGTM! @mohit355.. just resolve the conflicts @nish7898

**Comment by aashimgarg** [comment]
the branch still has conflicts

**Comment by aashimgarg** [comment]
@mohit355 LGTM.

**Comment by mohit355** [comment]
Successfully merged @nish7898

**Pull request merged**
