### PR TITLE
connected login page to backend

### PR DESCRIPTION
**Pull request by shrushti2000**
connected login page to backend

### CODE REVIEW

**Comment by aashimgarg** [comment]
please add a screencast with the whole auth setup.

**Comment by shrushti2000** [comment]
ezgif com-gif-maker (1)

**Comment by mohit355** [comment]
I think it's working properly @aashimgarg

**Review by aashimgarg — APPROVED** [review]

**Comment by aashimgarg** [comment]
@nish7898 have a look. later we are going to store the state in the redux.

**Pull request merged**
