### PR TITLE
Added the wireframe of homepage for Dhenu Seva

### PR DESCRIPTION
**Pull request by avinashbest**
- Wireframe for homepage added in directory wireframe
- Attached in pdf format.

### CODE REVIEW

**Review by mohit355 — COMMENTED** [review]
Send me the  pdf in group

**Comment by avinashbest** [comment]
Already given in group. I'm doing my contribution.

**Comment by mohit355** [comment]
We will be working on a new wireframe for Home Page

**Comment by aashimgarg** [comment]
Share the docs link or screenshots @avinashbest

**Comment by avinashbest** [comment]
image

**Comment by aashimgarg** [comment]
> image

This is not related to the theme. So @mohit355 please close this one

**Pull request closed without merging**
